[package]
name = "memeforge"
version = "0.1.0"
edition = "2024_07"

[features]
deprecated_legacy_map = []

[dependencies]
starknet = "2.11.4"
openzeppelin = "0.20.0"

[dev-dependencies]
snforge_std = "0.44.0"
assert_macros = "2.11.4"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std", "dojo"]

