# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

[sncast.default]                                         # Define a profile name
# url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_8" # Url of the RPC provider
# accounts-file = "~/.starknet_accounts/starknet_open_zephyr_accounts.json"                        # Path to the file with the account data
# account = "paps"                                     # Account from `accounts_file` or default account file that will be used for the transactions
# keystore = "../../../.starkli/keystore.json"                                  # Path to the keystore file
# wait-params = { timeout = 300, retry-interval = 10 }     # Wait for submitted transaction parameters
# block-explorer = "StarkScan"                             # Block explorer service used to display links to transaction details
# show-explorer-links = true                               # Print links pointing to pages with transaction details in the chosen block explorer

[sncast.devnet]
account = "account-1"
accounts-file = "/home/uche-ofatu/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050"